---
swagger: "2.0"
info:
  description: Api Documentation
  version: "1.0"
  title: Api Documentation
  termsOfService: urn:tos
  contact: {}
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0
host: localhost:18080
basePath: /
tags:
- name: host-controller
  description: Host Controller
- name: host-item-controller
  description: Host Item Controller
- name: host-storage-controller
  description: Host Storage Controller
- name: system-controller
  description: System Controller
paths:
  /api/v1/agent/host:
    get:
      tags:
      - host-controller
      summary: Get Host all list
      operationId: listUsingGET
      produces:
      - '*/*'
      parameters: []
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ResBody«PageableResBody«List«HostInfo»»»'
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
  /api/v1/agent/host/{hostSeq}:
    put:
      tags:
      - host-controller
      summary: Update request Host
      operationId: updateUsingPUT
      consumes:
      - application/json
      produces:
      - '*/*'
      parameters:
      - in: body
        name: hostInfo
        description: hostInfo
        required: true
        schema:
          $ref: '#/definitions/HostUpdateDTO'
      - name: hostSeq
        in: path
        description: hostSeq
        required: true
        type: integer
        format: int64
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ResBody«object»'
        "201":
          description: Created
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
  /api/v1/agent/host/{hostSeq}/item:
    get:
      tags:
      - host-item-controller
      summary: Get Host item all list
      operationId: listUsingGET_1
      produces:
      - '*/*'
      parameters:
      - name: hostSeq
        in: path
        description: hostSeq
        required: true
        type: integer
        format: int64
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ResBody«PageableResBody«List«HostItemInfo»»»'
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
    post:
      tags:
      - host-item-controller
      summary: Create request Host item
      operationId: createUsingPOST
      consumes:
      - application/json
      produces:
      - '*/*'
      parameters:
      - name: hostSeq
        in: path
        description: hostSeq
        required: true
        type: integer
        format: int64
      - in: body
        name: info
        description: info
        required: true
        schema:
          $ref: '#/definitions/HostItemCreateDTO'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ResBody«object»'
        "201":
          description: Created
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
  /api/v1/agent/host/{hostSeq}/item/{itemSeq}:
    put:
      tags:
      - host-item-controller
      summary: Update request Host item
      operationId: updateUsingPUT_1
      consumes:
      - application/json
      produces:
      - '*/*'
      parameters:
      - name: hostSeq
        in: path
        description: hostSeq
        required: true
        type: integer
        format: int64
      - in: body
        name: info
        description: info
        required: true
        schema:
          $ref: '#/definitions/HostItemUpdateDTO'
      - name: itemSeq
        in: path
        description: itemSeq
        required: true
        type: integer
        format: int64
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ResBody«object»'
        "201":
          description: Created
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
    delete:
      tags:
      - host-item-controller
      summary: Delete request Host item
      operationId: deleteUsingDELETE
      produces:
      - '*/*'
      parameters:
      - name: hostSeq
        in: path
        description: hostSeq
        required: true
        type: integer
        format: int64
      - name: itemSeq
        in: path
        description: itemSeq
        required: true
        type: integer
        format: int64
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ResBody«object»'
        "204":
          description: No Content
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
  /api/v1/agent/host/{hostSeq}/item/{itemSeq}/turnMonitoringYn:
    put:
      tags:
      - host-item-controller
      summary: Update request Host item monitoring state on/off
      operationId: turnMonitoringYnUsingPUT_1
      consumes:
      - application/json
      produces:
      - '*/*'
      parameters:
      - name: hostSeq
        in: path
        description: hostSeq
        required: true
        type: integer
        format: int64
      - name: itemSeq
        in: path
        description: itemSeq
        required: true
        type: integer
        format: int64
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ResBody«object»'
        "201":
          description: Created
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
  /api/v1/agent/host/{hostSeq}/storage:
    get:
      tags:
      - host-storage-controller
      summary: Get Host storage all list
      operationId: listUsingGET_2
      produces:
      - '*/*'
      parameters:
      - name: hostSeq
        in: path
        description: hostSeq
        required: true
        type: integer
        format: int64
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ResBody«PageableResBody«List«HostStorageInfo»»»'
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
    post:
      tags:
      - host-storage-controller
      summary: Create request Host storage
      operationId: createUsingPOST_1
      consumes:
      - application/json
      produces:
      - '*/*'
      parameters:
      - name: hostSeq
        in: path
        description: hostSeq
        required: true
        type: integer
        format: int64
      - in: body
        name: info
        description: info
        required: true
        schema:
          $ref: '#/definitions/HostStorageCreateDTO'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ResBody«object»'
        "201":
          description: Created
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
  /api/v1/agent/host/{hostSeq}/storage/{storageSeq}:
    put:
      tags:
      - host-storage-controller
      summary: Update request Host storage
      operationId: updateUsingPUT_2
      consumes:
      - application/json
      produces:
      - '*/*'
      parameters:
      - name: hostSeq
        in: path
        description: hostSeq
        required: true
        type: integer
        format: int64
      - in: body
        name: info
        description: info
        required: true
        schema:
          $ref: '#/definitions/HostStorageUpdateDTO'
      - name: storageSeq
        in: path
        description: storageSeq
        required: true
        type: integer
        format: int64
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ResBody«object»'
        "201":
          description: Created
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
    delete:
      tags:
      - host-storage-controller
      summary: Delete request Host storage
      operationId: deleteUsingDELETE_1
      produces:
      - '*/*'
      parameters:
      - name: hostSeq
        in: path
        description: hostSeq
        required: true
        type: integer
        format: int64
      - name: storageSeq
        in: path
        description: storageSeq
        required: true
        type: integer
        format: int64
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ResBody«object»'
        "204":
          description: No Content
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
  /api/v1/agent/host/{hostSeq}/storage/{storageSeq}/turnMonitoringYn:
    put:
      tags:
      - host-storage-controller
      summary: Update request Host storage monitoring state on/off
      operationId: turnMonitoringYnUsingPUT_2
      consumes:
      - application/json
      produces:
      - '*/*'
      parameters:
      - name: hostSeq
        in: path
        description: hostSeq
        required: true
        type: integer
        format: int64
      - name: storageSeq
        in: path
        description: storageSeq
        required: true
        type: integer
        format: int64
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ResBody«object»'
        "201":
          description: Created
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
  /api/v1/agent/host/{hostSeq}/synchronize:
    put:
      tags:
      - host-controller
      summary: Update request Host all config
      operationId: synchronizeAllUsingPUT
      consumes:
      - application/json
      produces:
      - '*/*'
      parameters:
      - name: hostSeq
        in: path
        description: hostSeq
        required: true
        type: integer
        format: int64
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ResBody«object»'
        "201":
          description: Created
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
  /api/v1/agent/host/{hostSeq}/turnMonitoringYn:
    put:
      tags:
      - host-controller
      summary: Update request Host monitoring state on/off
      operationId: turnMonitoringYnUsingPUT
      consumes:
      - application/json
      produces:
      - '*/*'
      parameters:
      - name: hostSeq
        in: path
        description: hostSeq
        required: true
        type: integer
        format: int64
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ResBody«object»'
        "201":
          description: Created
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
  /api/v1/agent/plugins:
    get:
      tags:
      - system-controller
      summary: Get all available config list
      operationId: getPluginsUsingGET
      produces:
      - '*/*'
      parameters: []
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ResBody«List«PluginDefInfo»»'
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
definitions:
  HostInfo:
    type: object
    properties:
      createAt:
        type: string
      description:
        type: string
      ex:
        type: string
      itemCount:
        type: integer
        format: int64
      monitoringYn:
        type: string
        enum:
        - "N"
        - "Y"
      name:
        type: string
      os:
        type: string
        enum:
        - LINUX
        - MACOS
        - SOLARIS
        - UNIX
        - WINDOWS
      seq:
        type: integer
        format: int64
      state:
        type: string
        enum:
        - ACTIVE
        - INACTIVE
      storageCount:
        type: integer
        format: int64
      syncYN:
        type: string
        enum:
        - "N"
        - "Y"
      telegrafState:
        type: string
        enum:
        - FAILED
        - RUNNING
        - STOPPED
      updateAt:
        type: string
      uuid:
        type: string
    title: HostInfo
  HostItemCreateDTO:
    type: object
    properties:
      intervalSec:
        type: integer
        format: int32
      name:
        type: string
      pluginSeq:
        type: integer
        format: int64
      setting:
        type: string
    title: HostItemCreateDTO
  HostItemInfo:
    type: object
    properties:
      createAt:
        type: string
      hostSeq:
        type: integer
        format: int64
      intervalSec:
        type: integer
        format: int32
      monitoringYn:
        type: string
        enum:
        - "N"
        - "Y"
      name:
        type: string
      pluginName:
        type: string
      pluginSeq:
        type: integer
        format: int64
      seq:
        type: integer
        format: int64
      setting:
        type: string
      state:
        type: string
        enum:
        - ADD
        - DELETE
        - NONE
        - UPDATE
      updateAt:
        type: string
    title: HostItemInfo
  HostItemUpdateDTO:
    type: object
    properties:
      intervalSec:
        type: integer
        format: int32
      name:
        type: string
      pluginSeq:
        type: integer
        format: int64
      setting:
        type: string
    title: HostItemUpdateDTO
  HostStorageCreateDTO:
    type: object
    properties:
      database:
        type: string
      name:
        type: string
      password:
        type: string
      retentionPolicy:
        type: string
      url:
        type: string
      username:
        type: string
    title: HostStorageCreateDTO
  HostStorageInfo:
    type: object
    properties:
      database:
        type: string
      hostSeq:
        type: integer
        format: int64
      monitoringYn:
        type: string
        enum:
        - "N"
        - "Y"
      name:
        type: string
      password:
        type: string
      retentionPolicy:
        type: string
      seq:
        type: integer
        format: int64
      state:
        type: string
        enum:
        - ADD
        - DELETE
        - NONE
        - UPDATE
      url:
        type: string
      username:
        type: string
    title: HostStorageInfo
  HostStorageUpdateDTO:
    type: object
    properties:
      database:
        type: string
      name:
        type: string
      password:
        type: string
      retentionPolicy:
        type: string
      url:
        type: string
      username:
        type: string
    title: HostStorageUpdateDTO
  HostUpdateDTO:
    type: object
    properties:
      description:
        type: string
      name:
        type: string
    title: HostUpdateDTO
  PageableResBody«List«HostInfo»»:
    type: object
    properties:
      records:
        type: integer
        format: int64
      rows:
        type: array
        items:
          $ref: '#/definitions/HostInfo'
    title: PageableResBody«List«HostInfo»»
  PageableResBody«List«HostItemInfo»»:
    type: object
    properties:
      records:
        type: integer
        format: int64
      rows:
        type: array
        items:
          $ref: '#/definitions/HostItemInfo'
    title: PageableResBody«List«HostItemInfo»»
  PageableResBody«List«HostStorageInfo»»:
    type: object
    properties:
      records:
        type: integer
        format: int64
      rows:
        type: array
        items:
          $ref: '#/definitions/HostStorageInfo'
    title: PageableResBody«List«HostStorageInfo»»
  PluginDefInfo:
    type: object
    properties:
      name:
        type: string
      os:
        type: array
        items:
          type: string
          enum:
          - LINUX
          - MACOS
          - SOLARIS
          - UNIX
          - WINDOWS
      pluginId:
        type: string
      seq:
        type: integer
        format: int64
    title: PluginDefInfo
  ResBody«HostInfo»:
    type: object
    properties:
      data:
        $ref: '#/definitions/HostInfo'
      rsCode:
        type: string
      rsMsg:
        type: string
    title: ResBody«HostInfo»
  ResBody«HostItemInfo»:
    type: object
    properties:
      data:
        $ref: '#/definitions/HostItemInfo'
      rsCode:
        type: string
      rsMsg:
        type: string
    title: ResBody«HostItemInfo»
  ResBody«HostStorageInfo»:
    type: object
    properties:
      data:
        $ref: '#/definitions/HostStorageInfo'
      rsCode:
        type: string
      rsMsg:
        type: string
    title: ResBody«HostStorageInfo»
  ResBody«List«PluginDefInfo»»:
    type: object
    properties:
      data:
        type: array
        items:
          $ref: '#/definitions/PluginDefInfo'
      rsCode:
        type: string
      rsMsg:
        type: string
    title: ResBody«List«PluginDefInfo»»
  ResBody«PageableResBody«List«HostInfo»»»:
    type: object
    properties:
      data:
        $ref: '#/definitions/PageableResBody«List«HostInfo»»'
      rsCode:
        type: string
      rsMsg:
        type: string
    title: ResBody«PageableResBody«List«HostInfo»»»
  ResBody«PageableResBody«List«HostItemInfo»»»:
    type: object
    properties:
      data:
        $ref: '#/definitions/PageableResBody«List«HostItemInfo»»'
      rsCode:
        type: string
      rsMsg:
        type: string
    title: ResBody«PageableResBody«List«HostItemInfo»»»
  ResBody«PageableResBody«List«HostStorageInfo»»»:
    type: object
    properties:
      data:
        $ref: '#/definitions/PageableResBody«List«HostStorageInfo»»'
      rsCode:
        type: string
      rsMsg:
        type: string
    title: ResBody«PageableResBody«List«HostStorageInfo»»»
  ResBody«object»:
    type: object
    properties:
      data:
        type: object
        properties: {}
      rsCode:
        type: string
      rsMsg:
        type: string
    title: ResBody«object»
