server:
  port: 18080

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://0.0.0.0:3306

mybatis:
  mapper-locations: mapper/*.xml
  configuration:
    cache-enabled: true
    lazy-loading-enabled: true
    multiple-result-sets-enabled: true
    use-column-label: true
    use-generated-keys: true
    default-executor-type: simple
    default-statement-timeout: 100
    map-underscore-to-camel-case: true
  type-aliases-package: mcmp.mc.observability.agent.model, mcmp.mc.observability.agent.dto
  type-handlers-package: mcmp.mc.observability.agent.util

logging:
  level:
    root: INFO