version: "3.9"

services:
  mariadb:
    image: mariadb:10.7.6
    ports:
      - 3306:3306
    volumes:
      - /data/docker/mariadb/etc/mysql/conf.d:/etc/mysql/conf.d:ro
      - /data/docker/mariadb/var/lib/mysql:/var/lib/mysql
      - /data/docker/mariadb/var/log/maria:/var/log/maria
      - ./maria_init.sql:/docker-entrypoint-initdb.d/maria_init.sql
    environment:
      - TZ="Asia/Seoul"
      - ALLOW_EMPTY_PASSWORD=no
      - MARIADB_ROOT_PASSWORD=qwe1212!Q
      - MARIADB_USER=mc-agent
      - MARIADB_DATABASE=mc_observability
      - MARIADB_PASSWORD=mc-agent

  influxdb:
    image: influxdb:1.8
    ports:
      - 8086:8086
    environment:
      - INFLUXDB_USER=mc-agent
      - INFLUXDB_PASSWORD=mc-agent
      - INFLUXDB_DB="mc-observability"
    volumes:
      - /data/docker/influxdb/config:/etc/influxdb
      - /data/docker/influxdb/var/lib/influxdb:/var/lib/influxdb

  chronograf:
    image: chronograf:1.10
    ports:
      - 8888:8888