server:
  port: 18080

deploy:
  site-code: m-cmp

spring:
  application:
    name: mc-o11y-manager
  datasource:
    url: jdbc:mariadb://${DATABASE_HOST:mc-observability-maria}:${DATABASE_PORT:3306}/${DATABASE_NAME:mc_observability}
    username: ${DATABASE_ID:mc-agent}
    password: ${DATABASE_PW:mc-agent}
    hikari:
      max-lifetime: 150000
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: false
        use_sql_comments: false
    open-in-view: false
    show-sql: false
  banner:
    location: classpath:banner.txt
  mail:
    host: ${SMTP_HOST:}
    port: ${SMTP_PORT:}
    username: ${SMTP_USERNAME:}
    password: ${SMTP_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: ${SMTP_AUTH:true}
          starttls:
            enable: ${SMTP_ENABLE_TLS:true}

springdoc:
  packages-to-scan: com.mcmp.o11ymanager.controller
  paths-to-match: "/**"
  paths-to-exclude:
    - "/api/**/test/**"
  api-docs:
    enabled: true
  swagger-ui:
    path: /api/docs
  default-produces-media-type: application/json

  mvc:
    converters:
      preferred-json-mapper: jackson
    jackson:
      default-property-inclusion: non_null
      serialization:
        fail-on-empty-beans: false
    http:
      encoding:
        charset: UTF-8
        enabled: true
        force: true
    messages:
      encoding: UTF-8

loki:
  url: http://mc-observability-loki:3100
  endpoints:
    query: /loki/api/v1/query
    range: /loki/api/v1/query_range

influxdb:
  url: http://mc-o11y-influxdb:8086
  database: ${INFLUXDB_DB:mc-observability}
  username: ${INFLUX_USER:mc-agent}
  password: ${INFLUX_PASS:mc-agent}

health:
  check-interval: 10000
  host-connection-check-timeout: 5000

ssh:
  connection-timeout: 10000
  ssh-connection-cache-timeout: 120000

feign:
  okhttp:
    enabled: true
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 30000
        loggerLevel: full
      LokiFeignClient:
        loggerLevel: full
  semaphore:
    url: http://mc-observability-infra:3000
    username: ${SEMAPHORE_USER:admin}
    password: ${SEMAPHORE_PASS:semaphorepass}
    project-name: ansible
    init-max-parallel-tasks: 10
    template-names:
      agent-install: install-agent
      agent-config-update: config-update
    task-check-scheduler:
      check-interval-sec: 5
      max-wait-minutes: 10
  cb-tumblebug:
    connect-timeout: 5000
    read-timeout: 600000
    url: ${TUMBLEBUG_URL:http://cb-tumblebug:1323}
    id: ${TUMBLEBUG_ID:default}
    pw: ${TUMBLEBUG_PW:default}
  cb-spider:
    url: ${SPIDER_URL:http://cb-spider:1024}
    id: ${SPIDER_ID:}
    pw: ${SPIDER_PW:}
  insight:
    url: ${INSIGHT_URL:http://mc-observability-insight:9001}

grafana:
  url: ${GRAFANA_URL:https://mc-observability-grafana:8443}
  api-key: ${GRAFANA_API_KEY:}

ollama:
  base-url: ${OLLAMA_BASE_URL:}

logging:
  level:
    org.apache.sshd.client: ERROR
    org.apache.sshd.common: ERROR
    com.mcmp.o11ymanager.infrastructure.log.client.LokiFeignClient: DEBUG
    feign: DEBUG
    feign.Logger: DEBUG
    feign.template: WARN
  file:
    path: /applog
    name: ${spring.application.name}
  logback:
    rollinpolicy:
      max-history: 14
      max-file-size: 200MB


