spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    show-sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type: TRACE
    org.hibernate.engine.transaction.internal.TransactionImpl: TRACE
    org.hibernate.type.descriptor.sql: TRACE
